### ISSUE TITLE
Event form should display general form errors (not just field errors)

### ISSUE THREAD

**Issue by gandalfar** [codeeu/coding-events#278]

**Comment by oana-sipos** [comment]
@gandalfar We are going through issues and trying to see which ones are still valid.
Can you please provide more details for this one? What do you mean by general form errors? 
Thank you!

**Comment by gandalfar** [comment]
@oana-sipos Please close all of my issues on this project.

**Comment by oana-sipos** [comment]
We are just asking for details, no need that you fix it. We want to fix whatever is worth fixing. Thank you!

**Comment by gandalfar** [comment]
@oana-sipos sorry, I don't remember much about the project after 2 years and I don't have time at the moment to revisit it.
