### ISSUE TITLE
codeweek.eu logo is blurry on retina display

### ISSUE THREAD

**Issue by goranche** [codeeu/coding-events#288]
it either needs to be replaced with a high-res version or code should be added to display different images depending on the display (preferably the latter)

the same goes for the other pages of codeweek.eu, not just events.  
on those pages the images in the footer (social media icons) seem to have the same problem

**Comment by oana-sipos** [comment]
Indeed, logo is not a vector. However, it seems it has been changed already, so I will create a new issue to even update it to the new one.
