### ISSUE TITLE
Changing contact information when adding event changes users email account

### ISSUE THREAD

**Issue by gandalfar** [codeeu/coding-events#311]
Steps to reproduce:

1. Login with Google
2. Add event and change email to something else
3. Logout
4. Login with Google again and events contact email will be overridden by the one used by Google

--

Not sure if it matters, just something I was thinking about while looking at #309

**Comment by oana-sipos** [comment]
Cannot reproduce. If you find a way to do so, please reopen the issue and share some printscreens, thank you.
