### ISSUE TITLE
Add registration status for an event

### ISSUE THREAD

**Issue by friedger** [codeeu/coding-events#382]
Event organizers should have the possibility to set the registration status: open, sold out, invite only, waiting list, closed, cancelled

Once the date of the event has passed, the registration status should be automatically set to closed.

Ideally, there is an api (e.g. the status is mirrored from eventbrite, meetup.com, ..)

Related to issue #120

**Comment by ioana-chiorean** [comment]
This is a bit out of our scope and being on limited resources we won't be able to implement it any time soon. 
We will encourage the organizers to use other tools for confirmation of status. 

Thanks for helping out!
