### ISSUE TITLE
Login in failed with Google Account

### ISSUE THREAD

**Issue by Lieke22** [codeeu/coding-events#407]
Hi all,

I'm trying to log in with my google account, but it says: "OpenID 2.0 for Google-accounts has ended".
So I'm not able to login at the website anymore.

**Comment by SteveClement** [comment]
We are on it :) Expect it working by the end of the week.
Thanks.

**Comment by SteveClement** [comment]
Dear @Lieke22 it should work now. Please test and let us know it's all good.

**Comment by SteveClement** [comment]
it does work now.
