### ISSUE TITLE
Scoreboard page has an UI bug

### ISSUE THREAD

**Issue by mitio** [codeeu/coding-events#417]
When scorlled down, the scoreboard grid goes over the main menu:
https://www.dropbox.com/s/wqqm2sodat93xqe/Screenshot%202015-09-28%2015.48.21.png?dl=0

Might be as simple as upping the `z-index` of the menu/header.

/cc @joseihf

**Comment by ercchy** [comment]
I belive my pull request #420 will fix this issue.

**Comment by mitio** [comment]
I can confirm this is now fixed. Thanks @ercchy!
