### ISSUE TITLE
Investigate and fix the pip install error in the Travis CI build

### ISSUE THREAD

**Issue by mitio** [codeeu/coding-events#432]
The erroring build: <https://travis-ci.org/codeeu/coding-events/builds/137719106>

It might be related to a missing module in the dependencies, or a module which has been yanked or renamed in the public repos.

**Comment by SteveClement** [comment]
It seems to be a virtualenv issue, potentially: https://stackoverflow.com/questions/35780537/error-no-module-named-markerlib-when-installing-some-packages-on-virtualenv

**Comment by SteveClement** [comment]
Fixed travis-build. For now ;)
If anything breaks, please let me know.

**Comment by mitio** [comment]
🙇
