### ISSUE TITLE
Embed map into other websites too

### ISSUE THREAD

**Issue by oana-sipos** [codeeu/coding-events#441]
To investigate and inform Germany's ambassadors

**Comment by mitio** [comment]
One thing that can be used is this URL:

http://events.codeweek.eu/map/

It shows only the map and it can be embedded in an iframe. It can be
improved by making the map use the full height of the window and by
allowing some filtration of the events or setting a custom map
zoom/center via query parameters.


There's also an API, which can be used for fetching info about the events.

**Comment by oana-sipos** [comment]
Thanks @mitio for shedding some light into this.
